services:
  server:
    build:
      context: .
      dockerfile: mini1.9.3/Dockerfile
    image: gamaweb/server:alpha
    container_name: gama-server
    restart: unless-stopped
    ports:
      - "5500:5500"
    environment:
      - NODE_ENV=production
      - PORT=5500
      - GAMA_PATH=/opt/gama-platform/headless/gama-headless.sh

  gama:
    build:
      context: .
      dockerfile: mini1.9.3/Dockerfile
      args:
        - VCS_REF=gama-local
    image: gamaweb/mini:local
    container_name: gamamini
    restart: unless-stopped
    ports:
      - "6868:6868"
    command: -socket 6868
